#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend joelondev.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 193292-web-01 54.152.134.145:80 check
        server 193292-web-02 34.229.189.40:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
